name: Client - Build and Release
on:
  workflow_dispatch:
    inputs:
      semver_update_type:
        description: 'Semantic Versioning Update type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

defaults:
  run:
    shell: bash

jobs:
  increment_tag:
    name: Increment Tag
    outputs:
      newTagVersion: ${{steps.increment_tag.outputs.version}}
    steps:
      - name: Increment Tag Version
        id: increment_tag
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: ${{github.event.inputs.semver_update_type}}
          github_token: ${{secrets.GITHUB_TOKEN}}

  build_and_release:
    name: ${{matrix.platformName}} Client Release
    needs: increment_tag
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
          - os: windows-2022
            platformName: Windows
            cmakeFlags: -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe
          - os: ubuntu-22.04
            platformName: Linux
            cmakeFlags: ""

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: 'true'

      - name: (Linux) Download Dependencies
        if: ${{matrix.platformName == 'Linux'}}
        uses: awalsh128/cache-apt-pkgs-action@v1.2.4
        with:
          packages: libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-gfx-dev libgtk-3-dev
          version: 1.0

      - name: (Windows) Set up Visual Studio environment
        if: ${{matrix.platformName == 'Windows'}}
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16'

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure
        run: cmake -S "." -B "Build" -DCMAKE_BUILD_TYPE=Release -G Ninja ${{matrix.cmakeFlags}}

      - name: Build
        run: ninja -C "Build" all

      - name: Package
        run: |
          cmake --install "Build" --prefix "Package" --config Release
          mkdir Repose
          mv Packages/Repose/Client/* Repose
          7z a "Repose_${{matrix.platformName}}.zip" "Repose/"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: Repose_${{matrix.platformName}}.zip
          tag_name: ${{needs.increment_tag.outputs.newTagVersion}}

  # (the sourcecode zip that comes with a release doesn't contain submodules, 
  #  so we need to make our own)
  archive_full_source:
    name: Archive Full Source
    needs: increment_tag
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: 'true'

      - name: Create Source Code Archive
        run: 7z a "FullSourceCode.zip" .

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: FullSourceCode.zip
          tag_name: ${{needs.increment_tag.outputs.newTagVersion}}
